import dotenv from 'dotenv';

dotenv.config();

const {
  RISQLAB_LOG_LEVEL,
  RISQLAB_LOG_DIRECTORY_PATH,

  RISQLAB_FRONT_DOMAIN,
  RISQLAB_FRONT_HOSTNAME,
  RISQLAB_FRONT_PORT,
  RISQLAB_FRONT_HTTPSECURE,

  RISQLAB_API_HOSTNAME,
  RISQLAB_API_PORT,
  RISQLAB_API_HTTPSECURE,
  RISQLAB_API_JWT_SECRET,

  RISQLAB_DB_HOST,
  RISQLAB_DB_PORT,
  RISQLAB_DB_USER,
  RISQLAB_DB_PASSWORD,
  RISQLAB_DB_DATABASE,

  COINMARKETCAP_API_KEY,
  COINMARKETCAP_CRYPTO_FETCH_LIMIT,

  // eslint-disable-next-line no-undef
} = process.env;

const Config = {
  RISQLAB_LOG_LEVEL: RISQLAB_LOG_LEVEL,
  RISQLAB_LOG_DIRECTORY_PATH: RISQLAB_LOG_DIRECTORY_PATH,

  RISQLAB_FRONT_DOMAIN: RISQLAB_FRONT_DOMAIN,
  RISQLAB_FRONT_HOSTNAME: RISQLAB_FRONT_HOSTNAME,
  RISQLAB_FRONT_PORT: RISQLAB_FRONT_PORT,
  RISQLAB_FRONT_HTTPSECURE:
    String(RISQLAB_FRONT_HTTPSECURE) === '1' ||
    String(RISQLAB_FRONT_HTTPSECURE).toLowerCase() === 'true',

  RISQLAB_API_HOSTNAME: RISQLAB_API_HOSTNAME,
  RISQLAB_API_PORT: RISQLAB_API_PORT,
  RISQLAB_API_HTTPSECURE:
    String(RISQLAB_API_HTTPSECURE) === '1' ||
    String(RISQLAB_API_HTTPSECURE).toLowerCase() === 'true',
  RISQLAB_API_JWT_SECRET: RISQLAB_API_JWT_SECRET,

  RISQLAB_DB_HOST: RISQLAB_DB_HOST,
  RISQLAB_DB_PORT: RISQLAB_DB_PORT,
  RISQLAB_DB_USER: RISQLAB_DB_USER,
  RISQLAB_DB_PASSWORD: RISQLAB_DB_PASSWORD,
  RISQLAB_DB_DATABASE: RISQLAB_DB_DATABASE,

  COINMARKETCAP_API_KEY: COINMARKETCAP_API_KEY,
  COINMARKETCAP_CRYPTO_FETCH_LIMIT: COINMARKETCAP_CRYPTO_FETCH_LIMIT,
};

export default Config;
