const RISQLAB_API_PORT = process.env.NEXT_PUBLIC_RISQLAB_API_PORT;
const RISQLAB_API_HOSTNAME = process.env.NEXT_PUBLIC_RISQLAB_API_HOSTNAME;
const RISQLAB_API_HTTPSECURE =
  String(process.env.NEXT_PUBLIC_RISQLAB_API_HTTPSECURE) === "1" ||
  String(process.env.NEXT_PUBLIC_RISQLAB_API_HTTPSECURE).toLowerCase() ===
    "true";

export { RISQLAB_API_PORT, RISQLAB_API_HOSTNAME, RISQLAB_API_HTTPSECURE };
