import {
  RISQLAB_API_PORT,
  RISQLAB_API_HOSTNAME,
  RISQLAB_API_HTTPSECURE,
} from "./config";

export const API_BASE_URL = `http${RISQLAB_API_HTTPSECURE ? "s" : ""}://${RISQLAB_API_HOSTNAME}${RISQLAB_API_HTTPSECURE ? "" : `:${RISQLAB_API_PORT}`}`;
